### ISSUE TITLE
Add decrement

### ISSUE THREAD

**Issue by AstraLuma** [atomicobject/odo#4]
Could you add a decrement option, so a semaphore or other resource counter could be implemented?

**Comment by silentbicycle** [comment]
It may be better to expose compare-and-swap directly: either update the counter from X to Y and return true or leave it along and return false (because something else changed the value first). Thoughts?

**Comment by astronouth7303** [comment]
My use case was some scripted server monitoring, so I could track when connections went to 0 and take action then, so I would much prefer more of the "just make it happen" mode than trying to handle failure.

**Comment by silentbicycle** [comment]
So in that case decrementing below 0 should be impossible?

Atomically decrementing and running another command on success could be useful.

**Comment by astronouth7303** [comment]
Yeah, dec below 0 should be impossible, although I'm not sure that applies to the general case?
